book/api/urls.py
from django.urls import path
from .api_views import ApiBook, AUDBook

app_name='api'

urlpatterns =[
    path('list/', ApiBook.as_view(),name='api-list-book'),
    path('update/<int:pk>/', AUDBook.as_view(),name='audbook'),
]

book/urls.py
from django.urls import path, re_path
from . import views
app_name='book'

urlpatterns = [
    path('',views.index, name='index'),
    path('list_book/', views.BookLisView.as_view(), name='booklist'),
    path('detail/<int:pk', views.BookDetailView.as_view(),name='bookdetail'),
    path('mybook/', views.BorrowerListUser.as_view(), name='list_borrowerl_user'),
    path('detail/<uuid:pk>/renew/', views.renew_book_librarian, name='renew'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('book.api.urls', namespace='api')),
]

book/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
# Create your models here.
from datetime import date


class Gener(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book gener')

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    summery = models.TextField()
    ISBN = models.CharField(max_length=13)
    gener = models.ManyToManyField(Gener)
    author = models.ForeignKey('Author', on_delete = models.SET_NULL, null=True)

    def __str__(self):
        return self.title

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_birth = models.DateField(null=True, blank=True)
    date_death = models.DateField(null=True, blank=True)    

    def __str__(self):
        return f'{self.first_name}-{self.last_name}'

class BookInstance(models.Model):
    LOAN_STATUS = (
        ('m', 'Maintence'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering=['due_back']

        permissions = (
            ('can_read_private_section','VIP User'),
            ('user_watcher','User Watcher'),
        )

    @property #for use in template
    def is_overdue(self):
        if self.dueback and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return f'{self.id}-{self.book.title}'
        

book/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

class RenewBookForm(forms.Form):
    renewal_data = forms.DateField()

    def clean_renewal_data(self):
        data = self.cleaned_data['renewal_data']   

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date renewak in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks = 4):
            raise ValidationError(_('your dont more than 4 week'))

        return data

book/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book, BookInstance, Author, Gener
# Create your views here.
from django.views import generic
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from .forms import RenewBookForm
from django.http import HttpResponseRedirect
from django.urls import reverse


def email_check(user):
    return user.email.endswith('@gmail.com')

@login_required
@permission_required('book.can_read_private_section')
@user_passes_test(email_check)
def index(request):
    
    user.has_perms = ('user.can_add')
    
    num_book = Book.objects.all().count()
    num_instance = BookInstance.objects.all().count()
    num_instance_available = BookInstance.objects.filter(status__exact = 'a' )
    num_author = Author.objects.count()

    context={
        'num_book':num_book,
        'num_instance':num_instance,
        'num_instance_available':num_instance_available,
        'num_author':num_author,
    } 
    return render(request, 'book/index.html', context)

class BookLisView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    model = Book
    paginate_by = 5
    login_url = 'accoints/login/'
    redirect_field_name = '/book'

    def test_func(self):
        return user.email.endswith('@gmail.com')

    #context_object_name = 'book_list'
    #template_name = 'book/book_list.html'
    #queryset = Book.objects.filter(title__icontains = 'python')[:5]

    #def get_queryset(self):
    #    return Book.objects.filter(title__icontains = 'python')[:5]

    #def get_context_data(self, **kwargs):
    #    context = super(BookLisView, self).get_context_data(**kwargs)
    #    context['my_book_list'] = Book.objects.all()
    #    return context


class BookDetailView(generic.DetailView):
    model = Book
    context_object_name = 'book'


class BorrowerListUser(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'book/borrower_lis_book.html'
    context_object_name = 'borrwoer'
    permission_required = 'book.can_read_private_section'
    def get_queryset(self):
        return BookInstance.objects.filter(borrower = self.request.user).filter(status__exact='o').order_by('due_back')


def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk = pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            return HttpResponseRedirect(reverse('all-borrower')) #revers for use names urls.py


    else:
        propsed_renewal_date = datetime.date.today() + datetime.timedelta(weeks = 3)
        form = RenewBookForm(initial = {'renewal_date' : propsed_renewal_date}) # default value form for 3 weeks after


    context = {
        'form':form,
        'book_inst':book_inst,
    }

    return render(request, 'book/book_renew_librarian.html', context)

media/templates/book/book_detail.html
{% extends 'shred/site.html' %}

{% block body %}
    
    <p>{{book.title}}</p>    
    <p>{{book.summary}}</p>
    <p>{{book.isbn}}</p>

{% endblock %}
<hr>
{% for copy in book.bookinstance_set.all %}
    {% if copy.status == 'a' %}
        <p>{{ copy.due_back}}</p>
        <p>{{ copy.imprint}}</p>
        <p>{{ copy.id}}</p>    
    {% endif %}
{% endfor %}

media/templates/book/book_list.html
{% extends 'shred/site.html' %}

{% block body %}
{% if book_list %}

    {% for book in book_list %}
        <h3>{{book.title}}</h3>
        <p>{{boo.summary}}</p>
        <hr>
    {% endfor %}

    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
            Page {{page_obj.number}} of {{page_obj.paginator.num_pages}} Pages
        {% if page_object.has_next %}
        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    {% endif %}
{% else %}
    <h1>not book !!!</h1>
{% endif %}

<!--
<h1>my book:</h1><br>
{% for mybook in my_book_list %}
    {{b.title}}
    {{b.summary}}
{% endfor %}
{% endblock %}
-->

media/templates/book/book_renew_librarian.html
{% extends 'shred/site.html' %}

{% block body %}
    {% if form.errors %}
        {% for error,message in form.error.items %}
            <div class="alert alert-danger" >{{error}} {{message}}</div>
        {% endfor %}
    {% endif %}
    <h1>Renew:{{book_inst.book.title}}</h1>
    <p>Borrower: {{book_inst.borrower}}</p>
    <p {% if book_inst.is_overdue %} class="text-danger" {% endif %}>Due back: {{book_inst.due_back}}</p>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="form_group">
                <label for="renew_date">{{form_renewal_date.label}}</label>
                {{form.form_renewal_date}}
            </div>
            <input type="btn btn-info" type="submit" value="submit">
        </form>

{% endblock %}

media/templates/book/borrower_lis_book.html
{% extends 'shred/site.html' %}


{% block body %}
    {% if  borrower%}
        <ul>
            {% for book_b in borrower %}
                <li class="{% if bokk_b.is_overdue %} text-danger {% else %} text-wite {% endif %}" >
                    <a href="{% url 'book:bookdetail' book_b.book.pk %}">{{ book_b.book.title }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="text-center text-wite ">There are no borrower</p>
    {% endif %}
    <hr>
    {% if perms.book.can_read_private_section %}
        <p>you are VIP user</p>
        {% if perms.book.user_watcher %}
            <small>Enter user name : <strong>{{user}}</strong></small>
        {% else %}
            <small style="color: tomato;" >you don't have permission</small>
        {% endif %}
    {% else %}
        <small style="color: tomato;">you don't have permission</small>
    {% endif %}
{% endblock %}

media/templates/book/index.html
{% extends 'shred/site.html' %}
{% block body %}
    <p>number of book:{{num_book}}</p>
    <p>number of instance:{{num_instance}}</p>
    <p>number of instance available:{{num_instqnce_available}}</p>
    <p>number of author:{{num_athor}}</p>
{% endblock %}

media/templates/shred/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

media/templates/shred/site.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %} {% endblock %} | Joe developer</title>
</head>
<body>
    {% include 'shred/nav.html' %}
    <div class="jumbotron">
    {% block body %}

    {% endblock %}
    </div>
    {% include 'shred/foot.html' %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>